version: 2.0

jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:2.2
        steps:
            - checkout
            - run:
                name: Restore packages
                command: 
                    dotnet restore
            - run:
                name: Build the app
                command:
                    dotnet build
            - run:
                name: Test the app
                command:
                    dotnet test --logger trx --results-directory "..\TestResults"
            - run:
                name: Prepare data
                when: always
                command: |
                    export PATH="$PATH:/root/.dotnet/tools"
                    dotnet tool install -g trx2junit
                    /root/.dotnet/tools/trx2junit TestResults/*.trx
            - store_test_results:
                path: TestResults
            - store_artifacts:
                path: TestResults
